### ISSUE TITLE
Allow passing --dev switch to odoo at startup

### ISSUE THREAD

**Issue by szabolcsmaj** [camptocamp/docker-odoo-project#161]
I used the `--dev` switch when developing odoo with my custom docker image. Passed `--dev=all` at startup and the service restarted when it detected changes in the XML files or in python codes. This ofter resulted in not needing to restart the whole application.

Am I missing something or the current project setup lacks this option completely?

**Comment by i-vyshnevska** [comment]
you can start the container with `--dev` sending it directly, but we don't have it in setup,
it is not needed in production for instance, plus during dev you may don't want this option to run

**Comment by szabolcsmaj** [comment]
Thank you @i-vyshnevska for your quick answer. I'm using `docker-compose` during development. How can I pass the `--dev` switch to the odoo container without overriding the `entrypoint`?

**Comment by simahawk** [comment]
`docker-compose run --rm odoo odoo --dev=foo --what-ever-you-like-to-pass-to-the-odoo-executable`

**Comment by szabolcsmaj** [comment]
I'm sorry, I didn't explain it properly. I meant where should I put the `--dev=all` switch in the `docker-compose.yml` file?

It looks like this ATM:

```
  odoo:
    build: odoo
    image: project-image:latest
    environment:
      - DEMO=True
      - MARABUNTA_MODE=demo
      - MARABUNTA_ALLOW_SERIE=True
      - LIST_DB=True
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - RUNNING_ENV=$ENV
      - DB_HOST=$PGHOST
      - DB_NAME=$PGDATABASE
      - DB_USER=$PGUSER
      - DB_PASSWORD=$PGPASSWORD
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - ADDONS_PATH=$ADDONS_PATH
    hostname: ${ENV}-${COMPOSE_PROJECT_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.port=8069"
      - "traefik.http.routers.odoo.rule=Host(`odoo.localhost`)"
      - "traefik.http.routers.odoo_long.rule=Host(`odoo.localhost`) && PathPrefix(`/longpolling/`)"
      - "traefik.http.services.odoo_long.loadbalancer.server.port=8072"
      - "docky.main.service=true"
      - "docky.user=odoo"
    links:
      - db
    volumes:
      - ./odoo:/odoo
      - odoo:/data/odoo
```
