### ISSUE TITLE
Can't run example project either

### ISSUE THREAD

**Issue by rrebollo** [camptocamp/docker-odoo-project#235]
Using ghcr.io/camptocamp/odoo-project 16.0-5.0.5 I'm getting "Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown"
I had to make some minor changes to my Dockerfile:

```
# syntax = docker/dockerfile:1.2
FROM ghcr.io/camptocamp/odoo-project:16.0-5.0.5

COPY ./src /odoo/src
COPY ./external-src /odoo/external-src
COPY ./VERSION /odoo/
USER root
COPY ./requirements.txt /odoo/
RUN chown -R odoo:odoo /odoo
USER odoo
RUN pip3 install -e /odoo/src

# Project's specifics packages
RUN cd /odoo && pip3 install -r requirements.txt

ENV ADDONS_PATH=/odoo/local-src,/odoo/external-src/enterprise,/odoo/src/addons
```

And this is my compose file:

```
services:
  odoo:
    image: odoo:16-custom
    build: 
      context: ./odoo/
      network: host
    volumes:
      - "odoo_data:/data/odoo"
      - "./odoo:/odoo"
      - "/home/rolando/gits/odoo/enterprise:/odoo/external-src/enterprise"
      - "/home/rolando/projects/mc/edicolombia/mc-addons:/odoo/local-src"
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - PROXY_MODE=true
      - DB_NAME=odoodb
      - ADMIN_PASSWD=odoo
      - ODOO_BASE_URL=odoo-edicolombia.docker.localhost
      - ODOO_REPORT_URL=http://odoo:8069
      - KWKHTMLTOPDF_SERVER_URL=http://kwkhtmltopdf:8080
    depends_on:
      - db
      - kwkhtmltopdf      
    labels:
      - traefik.enable=true
      - traefik.http.routers.co-edi-16.entrypoints=https
      - traefik.http.routers.co-edi-16.tls=true
    networks:
      - traefik_net
      - db_net
 
  kwkhtmltopdf:
    image: ghcr.io/acsone/kwkhtmltopdf:0.12.5-latest
    networks:
      - db_net

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - "db_data:/var/lib/postgresql/data"
    networks:
      - db_net
volumes:
  odoo_data:
  db_data:
version: "3.8"

services:
  odoo:
    image: odoo:16-custom
    build: 
      context: ./odoo/
      network: host
    volumes:
      - "odoo_data:/data/odoo"
      - "./odoo:/odoo"
      - "/home/rolando/gits/odoo/enterprise:/odoo/external-src/enterprise"
      - "/home/rolando/projects/mc/edicolombia/mc-addons:/odoo/local-src"
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - PROXY_MODE=true
      - DB_NAME=odoodb
      - ADMIN_PASSWD=odoo
      - ODOO_BASE_URL=odoo-edicolombia.docker.localhost
      - ODOO_REPORT_URL=http://odoo:8069
      - KWKHTMLTOPDF_SERVER_URL=http://kwkhtmltopdf:8080
    depends_on:
      - db
      - kwkhtmltopdf      
    labels:
      - traefik.enable=true
      - traefik.http.routers.co-edi-16.entrypoints=https
      - traefik.http.routers.co-edi-16.tls=true
    networks:
      - traefik_net
      - db_net
 
  kwkhtmltopdf:
    image: ghcr.io/acsone/kwkhtmltopdf:0.12.5-latest
    networks:
      - db_net

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - "db_data:/var/lib/postgresql/data"
    networks:
      - db_net
volumes:
  odoo_data:
  db_data:

networks:
  traefik_net:
    external: true
  db_net:
networks:
  traefik_net:
    external: true
  db_net:
```
Any help will be appreciated
