### ISSUE TITLE
Odoo closes connection to db

### ISSUE THREAD

**Issue by robindierckx** [camptocamp/docker-odoo-project#35]
Hi

I am new to docker, so apologies if my issue is not relevant.
I followed the installation instructions in '/example', built the odoo folder in an image called `odoo-custom` and launched the 3 containers into a swarm. Odoo seems to connect to db but immediately closes the connection.

Not sure if this is related, but the source github repository `camptocamp/docker-postgresql` is not available anymore

The 3 containers are ran into a swarm. Seems ok, except I would expect to see a port mapping like `0.0.0.0:5432->5432/tcp` for the db container :
```
robin@Robin-Ubuntu:~/workspace/creo2-odoo$ docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                NAMES
04c839dce2d0        odoo-custom:latest                   "docker-entrypoint..."   11 minutes ago      Up 11 minutes       8069/tcp, 8072/tcp   creo2-odoo_odoo.1.945oty059tk71li985hn0v8k1
12339c7d61b4        camptocamp/odoo-nginx:9.0-1.1.0      "/docker-entrypoin..."   11 minutes ago      Up 11 minutes       80/tcp               creo2-odoo_nginx.1.o0ubhx6x0kmfd6qcg598i9d9z
deca0735d0d2        camptocamp/postgresql:pg9.5-latest   "/docker-entrypoin..."   11 minutes ago      Up 11 minutes       5432/tcp             creo2-odoo_db.1.643ku2mczbapgrm5tw1rm4i48
```

Odoo logs: every time the connection is closed after setting the base url
```
robin@Robin-Ubuntu:~/workspace/creo2-odoo$ docker service logs creo2-odoo_odoo
creo2-odoo_odoo.1.945oty059tk7@Robin-Ubuntu    | Starting with UID : 999
creo2-odoo_odoo.1.945oty059tk7@Robin-Ubuntu    | Running with demo data
creo2-odoo_odoo.1.945oty059tk7@Robin-Ubuntu    | 2017/08/03 13:59:58 Waiting for: tcp://db:5432
creo2-odoo_odoo.1.945oty059tk7@Robin-Ubuntu    | 2017/08/03 13:59:58 Connected to tcp://db:5432
creo2-odoo_odoo.1.945oty059tk7@Robin-Ubuntu    | run-parts: executing /opt/odoo/start-entrypoint.d/000_set_base_url
creo2-odoo_odoo.1.945oty059tk7@Robin-Ubuntu    | Setting Base URL to domain http://localhost:8069
creo2-odoo_odoo.1.945oty059tk7@Robin-Ubuntu    | 2017-08-03 13:59:59,909 1 INFO odoodb odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections 
```

Db logs: Everything seems normal here, except maybe that I don't see any logs with regards to the connection
```
robin@Robin-Ubuntu:~/workspace/creo2-odoo$ docker service logs creo2-odoo_db
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  database system was interrupted; last known up at 2017-08-03 14:14:38 UTC
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  incomplete startup packet
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | FATAL:  the database system is starting up
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  database system was not properly shut down; automatic recovery in progress
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  redo starts at 0/2901B30
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  invalid record length at 0/2901C10
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  redo done at 0/2901BD8
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  MultiXact member wraparound protections are now enabled
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  database system is ready to accept connections
creo2-odoo_db.1.vzszc03xyz4x@Robin-Ubuntu    | LOG:  autovacuum launcher started
```
Finally, my docker-compose.yml file
```
# Composition for development

version: '3'

services:
  odoo:
    image: odoo-custom #this image has been built locally
    deploy:
        replicas: 1 #for development
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=testme
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - LOG_HANDLER=:WARN
      - DEMO=true
      #- ODOO_BASE_URL="http://localhost:8069"
      - MIGRATE=true # MIGRATE can be True or False and determines whether migration tool marabunta will be launched. By default migration will be launched.


  db:
    image: camptocamp/postgresql:pg9.5-latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "data-db:/var/lib/postgresql/data"

  # can be useful for dev when longpolling is required
  nginx:
    image: camptocamp/odoo-nginx:9.0-1.1.0
    depends_on:
      - odoo

volumes:
  data-odoo:
  data-db:

```
